var countries = [
    { id: 'AF', name: 'Afghanistan', currency_code: 'AFN', currency_name: 'Afghani', phone: '+93', language_code: 'ps', language_name: 'پښتو', demonym: 'Afghan' }, 
    { id: 'AL', name: 'Albania', currency_code: 'ALL', currency_name: 'Lek', phone: '+355', language_code: 'sq', language_name: 'Shqip', demonym: 'Albanian' }, 
    { id: 'DZ', name: 'Algeria', currency_code: 'DZD', currency_name: 'Dinar', phone: '+213', language_code: 'ar', language_name: 'العربية', demonym: 'Algerian' }, 
    { id: 'AD', name: 'Andorra', currency_code: 'EUR', currency_name: 'Euro', phone: '+376', language_code: 'ca', language_name: 'Català', demonym: 'Andorran' }, 
    { id: 'AO', name: 'Angola', currency_code: 'AOA', currency_name: 'Kwanza', phone: '+244', language_code: 'pt', language_name: 'Português', demonym: 'Angolan' }, 
    { id: 'AG', name: 'Antigua and Barbuda', currency_code: 'XCD', currency_name: '	East Caribbean Dollar', phone: '+1268', language_code: 'en', language_name: 'English', demonym: 'Antiguan' },
    { id: 'AR', name: 'Argentina', currency_code: 'ARS', currency_name: 'Peso', phone: '+54', language_code: 'es', language_name: 'Español', demonym: 'Argentinian' }, 
    { id: 'AM', name: 'Armenia', currency_code: 'AMD', currency_name: 'Dram', phone: '+374', language_code: 'hy', language_name: 'Հայերեն', demonym: 'Armenian' }, 
    { id: 'AU', name: 'Australia', currency_code: 'AUD', currency_name: 'Dollar', phone: '	+61', language_code: 'en', language_name: 'English', demonym: 'Australian' }, 
    { id: 'AT', name: 'Austria', currency_code: 'EUR', currency_name: 'Euro', phone: '+43', language_code: 'de', language_name: 'Deutsch', demonym: 'Austrian' }, 
    { id: 'AZ', name: 'Azerbaijan', currency_code: 'AZN', currency_name: 'Manat', phone: '+994', language_code: 'az', language_name: 'Azərbaycan dili', demonym: 'Azerbaijani' }, 
    { id: 'BS', name: 'The Bahamas', currency_code: 'BSD', currency_name: 'Dollar', phone: '+1242', language_code: 'en', language_name: 'English', demonym: 'Bahamian' }, 
    { id: 'BH', name: 'Bahrain', currency_code: 'BHD', currency_name: 'Dinar', phone: '+973', language_code: 'ar', language_name: 'العربية', demonym: 'Bahraini' }, 
    { id: 'BD', name: 'Bangladesh', currency_code: 'BDT', currency_name: 'Taka', phone: '+880', language_code: 'bn', language_name: 'বাংলা', demonym: 'Bengali' }, 
    { id: 'BB', name: 'Barbados', currency_code: 'BBD', currency_name: 'Dollar', phone: '+1246', language_code: 'en', language_name: 'English', demonym: 'Barbadian' }, 
    { id: 'BY', name: 'Belarus', currency_code: 'BYR', currency_name: 'Ruble', phone: '+375', language_code: 'be', language_name: 'беларуская мова', demonym: 'Belarusian' }, 
    { id: 'BE', name: 'Belgium', currency_code: 'EUR', currency_name: 'Euro', phone: '+32', language_code: 'nl', language_name: 'Flemish', demonym: 'Belgian' }, 
    { id: 'BZ', name: 'Belize', currency_code: 'BZD', currency_name: 'Dollar', phone: '+501', language_code: 'en', language_name: 'English', demonym: 'Belizean' }, 
    { id: 'BJ', name: 'Benin', currency_code: 'XOF', currency_name: 'West Africa Franc', phone: '+229', language_code: 'fr', language_name: 'Français', demonym: 'Beninois' }, 
    { id: 'BT', name: 'Bhutan', currency_code: 'BTN', currency_name: 'Ngultrum', phone: '+975', language_code: 'dz', language_name: 'Dzongkha', demonym: 'Bhutanese' }, 
    { id: 'BO', name: 'Bolivia', currency_code: 'BOB', currency_name: 'Boliviano', phone: '+591', language_code: 'es', language_name: 'Español', demonym: 'Bolivian' }, 
    { id: 'BA', name: 'Bosnia and Herzegovina', currency_code: 'BAM', currency_name: 'Mark', phone: '+387', language_code: 'bs', language_name: 'Bosanski', demonym: 'Bosnian' }, 
    { id: 'BW', name: 'Botswana', currency_code: 'BWP', currency_name: 'Pula', phone: '+267', language_code: 'en', language_name: 'English', demonym: 'Batswana' }, 
    { id: 'BR', name: 'Brazil', currency_code: 'BRL', currency_name: 'Real', phone: '+55', language_code: 'pt', language_name: 'Português', demonym: 'Brazilian' }, 
    { id: 'BN', name: 'Brunei', currency_code: 'BND', currency_name: 'Dollar', phone: '+673', language_code: 'ms', language_name: 'Bahasa Melayu', demonym: 'Bruneian' }, 
    { id: 'BG', name: 'Bulgaria', currency_code: 'BGN', currency_name: 'Lev', phone: '+359', language_code: 'bg', language_name: 'български език', demonym: 'Bulgarian' }, 
    { id: 'BF', name: 'Burkina Faso', currency_code: 'XOF', currency_name: 'West Africa Franc', phone: '+226', language_code: 'fr', language_name: 'Français', demonym: 'Burkinabe' }, 
    { id: 'BI', name: 'Burundi', currency_code: 'BIF', currency_name: 'Franc', phone: '+257', language_code: 'fr', language_name: 'Français', demonym: 'Burundian' }, 
    { id: 'KH', name: 'Cambodia', currency_code: 'KHR', currency_name: 'Riel', phone: '+855', language_code: 'km', language_name: 'ភាសាខ្មែរ', demonym: 'Cambodian' }, 
    { id: 'CM', name: 'Cameroon', currency_code: 'XAF', currency_name: 'Central African Franc', phone: '+237', language_code: 'fr', language_name: 'Français', demonym: 'Cameroonian' }, 
    { id: 'CA', name: 'Canada', currency_code: 'CAD', currency_name: 'Dollar', phone: '+1', language_code: 'en', language_name: 'English', demonym: 'Canadian' }, 
    { id: 'CV', name: 'Cape Verde', currency_code: 'CVE', currency_name: 'Escudo', phone: '+238', language_code: 'pt', language_name: 'Português', demonym: 'Cape Verdean' }, 
    { id: 'CF', name: 'Central African Republic', currency_code: 'XAF', currency_name: 'Franc', phone: '+236', language_code: 'fr', language_name: 'Français', demonym: 'Central African' }, 
    { id: 'TD', name: 'Chad', currency_code: 'XAF', currency_name: 'Central African Franc', phone: '+235', language_code: 'fr', language_name: 'Français', demonym: 'Chadian' }, 
    { id: 'CL', name: 'Chile', currency_code: 'CLP', currency_name: 'Peso', phone: '+56', language_code: 'es', language_name: 'Español', demonym: 'Chilean' }, 
    { id: 'CN', name: 'China', currency_code: 'CNY', currency_name: 'Yuan', phone: '+86', language_code: 'zh', language_name: '华语', demonym: 'Chinese' }, 
    { id: 'CO', name: 'Colombia', currency_code: 'COP', currency_name: 'Peso', phone: '+57', language_code: 'es', language_name: 'Español', demonym: 'Colombian' }, 
    { id: 'KM', name: 'Comoros', currency_code: 'KMF', currency_name: 'Franc', phone: '+269', language_code: 'fr', language_name: 'Français', demonym: 'Comorian' }, 
    { id: 'CD', name: 'Democratic Congo', currency_code: 'CDF', currency_name: 'Franc', phone: '+243', language_code: 'fr', language_name: 'Français', demonym: 'Congolese' }, 
    { id: 'CG', name: 'Congo', currency_code: 'XAF', currency_name: 'Central African Franc', phone: '+242', language_code: 'fr', language_name: 'Français', demonym: 'Congolese' }, 
    { id: 'CR', name: 'Costa Rica', currency_code: 'CRC', currency_name: 'Colón', phone: '+506', language_code: 'es', language_name: 'Español', demonym: 'Costa Rican' }, 
    { id: 'HR', name: 'Croatia', currency_code: 'HRK', currency_name: 'Kuna', phone: '+385', language_code: 'hr', language_name: 'hrvatski', demonym: 'Croatian' }, 
    { id: 'CU', name: 'Cuba', currency_code: 'CUC', currency_name: 'Convertible Peso', phone: '+53', language_code: 'es', language_name: 'Español', demonym: 'Cuban' }, 
    { id: 'CY', name: 'Cyprus', currency_code: 'EUR', currency_name: 'Euro', phone: '+357', language_code: 'el', language_name: 'ελληνικά', demonym: 'Cypriot' }, 
    { id: 'CZ', name: 'Czech Republic', currency_code: 'CZK', currency_name: 'Koruna', phone: '+420', language_code: 'cs', language_name: 'čeština', demonym: 'Czech' }, 
    { id: 'DK', name: 'Denmark', currency_code: 'DKK', currency_name: 'Krone', phone: '+45', language_code: 'da', language_name: 'Dansk', demonym: 'Danish' }, 
    { id: 'DJ', name: 'Djibouti', currency_code: 'DJF', currency_name: 'Franc', phone: '+253', language_code: 'fr', language_name: 'Français', demonym: 'Djiboutian' }, 
    { id: 'DM', name: 'Dominica', currency_code: 'XCD', currency_name: 'East Caribbean Dollar', phone: '+1767', language_code: 'en', language_name: 'English', demonym: 'Dominican' }, 
    { id: 'DO', name: 'Dominican Republic', currency_code: 'DOP', currency_name: 'Peso', phone: '+1849', language_code: 'es', language_name: 'Español', demonym: 'Dominican' }, 
    { id: 'TL', name: 'East Timor', currency_code: 'USD', currency_name: 'United States Dollar', phone: '+670', language_code: 'pt', language_name: 'Português', demonym: 'East Timorese' }, 
    { id: 'EC', name: 'Ecuador', currency_code: 'USD', currency_name: 'United States Dollar', phone: '+593', language_code: 'es', language_name: 'Español', demonym: 'Ecuadorian' }, 
    { id: 'EG', name: 'Egypt', currency_code: 'EGP', currency_name: 'Pound', phone: '+20', language_code: 'ar', language_name: 'العربية', demonym: 'Egyptian' }, 
    { id: 'SV', name: 'El Salvador', currency_code: 'USD', currency_name: 'United States Dollar', phone: '+503', language_code: 'es', language_name: 'Español', demonym: 'Salvadoran' }, 
    { id: 'GQ', name: 'Equatorial Guinea', currency_code: 'XAF', currency_name: 'Central African Franc', phone: '+240', language_code: 'es', language_name: 'Español', demonym: 'Equatoguinean' }, 
    { id: 'ER', name: 'Eritrea', currency_code: 'ERN', currency_name: 'Nakfa', phone: '+291', language_code: 'en', language_name: 'English', demonym: 'Eritrean' }, 
    { id: 'EE', name: 'Estonia', currency_code: 'EUR', currency_name: 'Euro', phone: '+372', language_code: 'et', language_name: 'Eesti keel', demonym: 'Estonian' }, 
    { id: 'ET', name: 'Ethiopia', currency_code: 'ETB', currency_name: 'Birr', phone: '+251', language_code: 'am', language_name: 'አማርኛ', demonym: 'Ethiopian' }, 
    { id: 'FJ', name: 'Fiji', currency_code: 'FJD', currency_name: 'Dollar', phone: '+679', language_code: 'en', language_name: 'English', demonym: 'Fijian' }, 
    { id: 'FI', name: 'Finland', currency_code: 'EUR', currency_name: 'Euro', phone: '+358', language_code: 'fi', language_name: 'Suomen kieli', demonym: 'Finnish' }, 
    { id: 'FR', name: 'France', currency_code: 'XPF', currency_name: 'Franc', phone: '+33', language_code: 'fr', language_name: 'Français', demonym: 'French' }, 
    { id: 'GA', name: 'Gabon', currency_code: 'XAF', currency_name: 'Central African Franc', phone: '+241', language_code: 'fr', language_name: 'Français', demonym: 'Gabonaise' }, 
    { id: 'GM', name: 'The Gambia', currency_code: 'GMD', currency_name: 'Dalasi', phone: '+220', language_code: 'en', language_name: 'English', demonym: 'Gambian' }, 
    { id: 'GE', name: 'Georgia', currency_code: 'GEL', currency_name: 'Lari', phone: '+995', language_code: 'ka', language_name: 'ქართული', demonym: 'Georgian' }, 
    { id: 'DE', name: 'Germany', currency_code: 'EUR', currency_name: 'Euro', phone: '+49', language_code: 'de', language_name: 'Deutsch', demonym: 'German' }, 
    { id: 'GH', name: 'Ghana', currency_code: 'GHS', currency_name: 'Cedi', phone: '+233', language_code: 'en', language_name: 'English', demonym: 'Ghanaian' }, 
    { id: 'GR', name: 'Greece', currency_code: 'EUR', currency_name: 'Euro', phone: '+30', language_code: 'el', language_name: 'ελληνικά', demonym: 'Greek' }, 
    { id: 'GD', name: 'Grenada', currency_code: 'XCD', currency_name: 'East Caribbean Dollar', phone: '+1-473', language_code: 'en', language_name: 'English', demonym: 'Grenadian' }, 
    { id: 'GT', name: 'Guatemala', currency_code: 'GTQ', currency_name: 'Quetzal', phone: '+502', language_code: 'es', language_name: 'Español', demonym: 'Guatemalan' }, 
    { id: 'GN', name: 'Guinea', currency_code: 'GNF', currency_name: 'Franc', phone: '+224', language_code: 'fr', language_name: 'Français', demonym: 'Guinean' }, 
    { id: 'GW', name: 'Guinea-Bissau', currency_code: 'XOF', currency_name: 'West African Franc', phone: '+245', language_code: 'pt', language_name: 'Português', demonym: 'Bissau-Guinean' }, 
    { id: 'GY', name: 'Guyana', currency_code: 'GYD', currency_name: 'Dollar', phone: '+592', language_code: 'en', language_name: 'English', demonym: 'Guyanese' }, 
    { id: 'HT', name: 'Haiti', currency_code: '', currency_name: 'Gourde', phone: '+509', language_code: 'fr', language_name: 'Français', demonym: 'Haitian' }, 
    { id: 'HN', name: 'Honduras', currency_code: 'HNL', currency_name: 'Lempira', phone: '+504', language_code: 'es', language_name: 'Español', demonym: 'Honduran' }, 
    { id: 'HU', name: 'Hungary', currency_code: 'HUF', currency_name: 'Forint', phone: '+36', language_code: 'hu', language_name: 'Magyar', demonym: 'Hungarian' }, 
    { id: 'IS', name: 'Iceland', currency_code: 'ISK', currency_name: 'Króna', phone: '+354', language_code: 'is', language_name: 'íslenska', demonym: 'Icelandic' }, 
    { id: 'IN', name: 'India', currency_code: 'INR', currency_name: 'Rupee', phone: '+91', language_code: 'hi', language_name: 'हिन्दी', demonym: 'Indian' }, 
    { id: 'ID', name: 'Indonesia', currency_code: 'IDR', currency_name: 'Rupiah', phone: '+62', language_code: 'id', language_name: 'Bahasa Indonesia', demonym: 'Indonesian' }, 
    { id: 'IR', name: 'Iran', currency_code: 'IRR', currency_name: 'Rial', phone: '+98', language_code: 'fa', language_name: 'فارسی', demonym: 'Iranian' }, 
    { id: 'IQ', name: 'Iraq', currency_code: 'IQD', currency_name: 'Dinar', phone: '+964', language_code: 'ar', language_name: 'العربية', demonym: 'Iraqi' }, 
    { id: 'IE', name: 'Ireland', currency_code: 'EUR', currency_name: 'Euro', phone: '+353', language_code: 'en', language_name: 'English', demonym: '	Irish' }, 
    { id: 'IL', name: 'Israel', currency_code: 'ILS', currency_name: 'New Shekel', phone: '	+972', language_code: 'he', language_name: 'עִבְרִית', demonym: 'Israeli' }, 
    { id: 'IT', name: 'Italy', currency_code: 'EUR', currency_name: 'Euro', phone: '+39', language_code: 'it', language_name: 'Italiano', demonym: 'Italian' }, 
    { id: 'CI', name: 'Ivory Coast', currency_code: 'XOF', currency_name: 'West African Franc', phone: '+225', language_code: 'fr', language_name: 'Français', demonym: 'Ivorian' },
    { id: 'JM', name: 'Jamaica', currency_code: 'JMD', currency_name: 'Dollar', phone: '+1658', language_code: 'en', language_name: 'English', demonym: 'Jamaican' },
    { id: 'JP', name: 'Japan', currency_code: 'JPY', currency_name: 'Yen', phone: '', language_code: 'ja', language_name: '日本語', demonym: 'Japanese' },
    { id: 'JO', name: 'Jordan', currency_code: 'JOD', currency_name: 'Dinar', phone: '+962', language_code: 'ar', language_name: 'العربية', demonym: 'Jordanian' },
    { id: 'KZ', name: 'Kazakhstan', currency_code: 'KZT', currency_name: 'Tenge', phone: '+76', language_code: 'kk', language_name: 'Kazakh', demonym: 'Kazakhstani' },
    { id: 'KE', name: 'Kenya', currency_code: 'KES', currency_name: 'Shilling', phone: '+254', language_code: 'en', language_name: 'English', demonym: 'Kenyan' },
    { id: 'KI', name: 'Kiribati', currency_code: 'AUD', currency_name: 'Australian Dollar', phone: '+686', language_code: 'en', language_name: 'English', demonym: 'Kiribati' },
    { id: 'KP', name: 'North Korea', currency_code: 'KPW', currency_name: 'Won', phone: '+850', language_code: 'ko', language_name: '조선어', demonym: 'North Korean' },
    { id: 'KR', name: 'South Korea', currency_code: 'KRW', currency_name: 'Won', phone: '+82', language_code: 'ko', language_name: '한국어', demonym: 'South Korean' },
    { id: 'KW', name: 'Kuwait', currency_code: 'KWD', currency_name: 'Dinar', phone: '+965', language_code: 'ar', language_name: 'العربية', demonym: 'Kuwaiti' },
    { id: 'KG', name: 'Kyrgyzstan', currency_code: 'KGS', currency_name: 'Som', phone: '+996', language_code: '	ky', language_name: 'Kyrgyz', demonym: 'Kyrgyz' },
    { id: 'LA', name: 'Laos', currency_code: 'LAK', currency_name: 'Kip', phone: '+856', language_code: 'lo', language_name: 'ພາສາລາວ', demonym: 'Laotian' },
    { id: 'LV', name: 'Latvia', currency_code: 'EUR', currency_name: 'Euro', phone: '+371', language_code: 'lv', language_name: 'Latviešu Valoda', demonym: 'Latvian' },
    { id: 'LB', name: 'Lebanon', currency_code: 'LBP', currency_name: 'Pound', phone: '+961', language_code: 'ar', language_name: 'العربية', demonym: 'Lebanese' },
    { id: 'LS', name: 'Lesotho', currency_code: 'LSL', currency_name: 'Loti', phone: '+266', language_code: 'en', language_name: 'English', demonym: 'Lesotho' },
    { id: 'LR', name: 'Liberia', currency_code: 'LRD', currency_name: 'Dollar', phone: '+231', language_code: 'en', language_name: 'English', demonym: 'Liberian' },
    { id: 'LY', name: 'Libya', currency_code: 'LYD', currency_name: 'Dinar', phone: '+	218', language_code: 'ar', language_name: 'العربية', demonym: 'Libyan' },
    { id: 'LI', name: 'Liechtenstein', currency_code: 'CHF', currency_name: 'Swiss Franc', phone: '+423', language_code: 'de', language_name: 'Deutsch', demonym: 'Liechtenstein' },
    { id: 'LT', name: 'Lithuania', currency_code: 'EUR', currency_name: 'Euro', phone: '+370', language_code: 'lt', language_name: 'Lietuvių kalba', demonym: 'Lithuanian' },
    { id: 'LU', name: 'Luxembourg', currency_code: 'EUR', currency_name: 'Euro', phone: '+352', language_code: 'lb', language_name: 'Lëtzebuergesch', demonym: 'Luxembourg' },
    /*{ id: '', name: '', currency_code: '', currency_name: '', phone: '', language_code: '', language_name: '', demonym: '' }*/
];

Array.prototype.forEach.call(document.querySelectorAll('table tbody'), function(elem){
    var columnTable = '';
    countries.forEach(function(res){
        columnTable += '<tr>';
        columnTable += '<td>'+res.id+'</td>';
        columnTable += '<td>'+res.name+'</td>';
        columnTable += '<td>'+res.currency_name+' ('+res.currency_code+')</td>';
        columnTable += '<td>'+res.language_name+' ('+res.language_code+'-'+res.id+')</td>';
        columnTable += '<td>'+res.phone+'</td>';
        columnTable += '<td>'+res.demonym+'</td>';
        columnTable += '</tr>';
    });
    elem.innerHTML = columnTable;
});
